### ISSUE TITLE
No Public API on Ghost 2.11.0

### ISSUE THREAD

**Issue by Rahulsharma0810** [wdiazux/cusca#14]
From 2.11.0 release there is no option of Enabling Public API in Labs Section.
https://forum.ghost.org/t/public-api-gone-in-ghost-version-2-11-0/5114

Will this theme still work with current latest version 2.28.x ?

**Comment by wdiazux** [comment]
The version 2.0.3 of this theme has support for Ghost 3.0. The information to how to get the API key was added to the README
